### ISSUE TITLE
Docker image build does not run hmmpress

### ISSUE THREAD

**Issue by jason-c-kwan** [KwanLab/Autometa#132]
## Current Behavior

Built the docker image from the nextflow PR (PR #118, commit 0e032f1f914a131804e45e31c68abb4ea678111b), and when trying to run `autometa-markers`, I get an error because the marker hmm database is not pressed.

### Steps to Reproduce

```
# First build the docker image from the commit above, then run it in interactive mode
# Use the files from the 78 Mbp simulated dataset
autometa-markers --orfs orfs.faa.gz --kingdom bacteria --hmmscan bacteria.hmmscan.tsv --out bacteria.markers.tsv
```

## Expected Behavior

Either the database should be pressed at build time (or during the conda install step), or when hmmscan needs to be run a check should be made that the database is pressed already.

## Environment Information

<details open><summary><code>autometa --check-dependencies --debug</code></summary><p>

```
See above
```
</p></details>

## Run Information

<details><summary><code>cat path/to/your/input/metagenome.config</code></summary><p>

```

```
</p></details>

<details><summary><code>cat path/to/your/outdir/metagenome.config</code></summary><p>

```

```
</p></details>

<details><summary>Log information generated by autometa. If you have run
autometa with the <code>--log</code> flag, e.g. <code>autometa <your-input> --log <logfile></code>
 then use the contents of the logfile.</summary><p>

```
[03/12/2021 06:44:39 PM DEBUG] autometa.common.external.hmmer: hmmscan --seed 42 --cpu 0 --tblout bacteria.hmmscan.tsv /opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/databases/markers/bacteria.single_copy.hmm /test_data/orfs.faa.gz
[03/12/2021 06:44:39 PM WARNING] autometa.common.external.hmmer: Make sure your hmm profiles are pressed! hmmpress -f /opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/databases/markers/bacteria.single_copy.hmm
Traceback (most recent call last):
  File "/opt/conda/bin/autometa-markers", line 33, in <module>
    sys.exit(load_entry_point('Autometa==2.0a0', 'console_scripts', 'autometa-markers')())
  File "/opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/common/markers.py", line 243, in main
    get(
  File "/opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/common/markers.py", line 160, in get
    scans = hmmer.hmmscan(
  File "/opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/common/external/hmmer.py", line 192, in hmmscan
    annotate_sequential(
  File "/opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/common/external/hmmer.py", line 124, in annotate_sequential
    raise err
  File "/opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/common/external/hmmer.py", line 119, in annotate_sequential
    subprocess.run(
  File "/opt/conda/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['hmmscan', '--seed', '42', '--cpu', '0', '--tblout', 'bacteria.hmmscan.tsv', '/opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/databases/markers/bacteria.single_copy.hmm', '/test_data/orfs.faa.gz']' returned non-zero exit status 1.
```
</p></details>

**Comment by jason-c-kwan** [comment]
The following also did not fix the error.

```
cd /autometa/databases/markers
hmmpress -f bacteria.single_copy.hmm
```

I still get:

```
[03/12/2021 06:52:10 PM DEBUG] autometa.common.external.hmmer: hmmscan --seed 42 --cpu 0 --tblout bacteria.hmmscan.tsv /opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/databases/markers/bacteria.single_copy.hmm /test_data/orfs.faa.gz
[03/12/2021 06:52:10 PM WARNING] autometa.common.external.hmmer: Make sure your hmm profiles are pressed! hmmpress -f /opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/databases/markers/bacteria.single_copy.hmm
Traceback (most recent call last):
  File "/opt/conda/bin/autometa-markers", line 33, in <module>
    sys.exit(load_entry_point('Autometa==2.0a0', 'console_scripts', 'autometa-markers')())
  File "/opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/common/markers.py", line 243, in main
    get(
  File "/opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/common/markers.py", line 160, in get
    scans = hmmer.hmmscan(
  File "/opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/common/external/hmmer.py", line 192, in hmmscan
    annotate_sequential(
  File "/opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/common/external/hmmer.py", line 124, in annotate_sequential
    raise err
  File "/opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/common/external/hmmer.py", line 119, in annotate_sequential
    subprocess.run(
  File "/opt/conda/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['hmmscan', '--seed', '42', '--cpu', '0', '--tblout', 'bacteria.hmmscan.tsv', '/opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/databases/markers/bacteria.single_copy.hmm', '/test_data/orfs.faa.gz']' returned non-zero exit status 1.
```

**Comment by WiscEvan** [comment]
I'm thinking this is because the ORFs are gzipped. Does hmmer handle gzipped files?

**Comment by jason-c-kwan** [comment]
Why are there some files that we can handle gzipped and others we can't? From a user perspective it is hard to predict. Perhaps we should just handle it ourselves if hmmer can't.

**Comment by WiscEvan** [comment]
> I'm thinking this is because the ORFs are gzipped. Does hmmer handle gzipped files?

HMMER handles gzipped ORFs.

This is an issue with the databases that have been passed. the default path is in the python installation path rather than the more intuitive path of `$HOME/Autometa/autometa/databases`

Notice Autometa default searches for 

```bash
/opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/databases/markers/bacteria.single_copy.hmm
```

rather than the source directory (pre-install). This should be updated in the Docker build
