### ISSUE TITLE
Reformat autometa-binning arguments

### ISSUE THREAD

**Issue by jason-c-kwan** [KwanLab/Autometa#133]
## Current Behavior

When going through the documentation section "running autometa" in sequence, the `autometa-binning` command will fail because autometa-kmers already run.

### Steps to Reproduce

```
autometa-kmers ...
autometa-binning kmers_norm.tsv coverage_table.tsv markers.tsv.gz bacteria_binning.tsv --embedded-kmers embedded_kmers.tsv --taxonomy taxonomy.tsv.gz --clustering-method dbscan --domain bacteria
```

## Expected Behavior

If a user goes through the walk through in the documentation, it should not give errors! Also, perhaps the autometa-binning entrypoint should be able to tolerate the k-mers table already being there?

## Environment Information

<details open><summary><code>autometa --check-dependencies --debug</code></summary><p>

```
Built the Dockerfile from the nextflow PR (commit 0e032f1f914a131804e45e31c68abb4ea678111b)
```
</p></details>

## Run Information

<details><summary><code>cat path/to/your/input/metagenome.config</code></summary><p>

```

```
</p></details>

<details><summary><code>cat path/to/your/outdir/metagenome.config</code></summary><p>

```

```
</p></details>

<details><summary>Log information generated by autometa. If you have run
autometa with the <code>--log</code> flag, e.g. <code>autometa <your-input> --log <logfile></code>
 then use the contents of the logfile.</summary><p>

```
[03/12/2021 07:00:16 PM DEBUG] autometa.common.kmers: k-mers frequency embedding already exists embedded_kmers.tsv
Traceback (most recent call last):
  File "/opt/conda/bin/autometa-binning", line 33, in <module>
    sys.exit(load_entry_point('Autometa==2.0a0', 'console_scripts', 'autometa-binning')())
  File "/opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/binning/recursive_dbscan.py", line 787, in main
    markers_df = load_markers(args.markers)
  File "/opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/common/markers.py", line 76, in load
    grouped_df = df.groupby("contig")["sacc"]
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 1542, in __getitem__
    return super().__getitem__(key)
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/base.py", line 280, in __getitem__
    raise KeyError(f"Column not found: {key}")
KeyError: 'Column not found: sacc'
```
</p></details>

**Comment by WiscEvan** [comment]
Looks like you’ve provided the kmers table where you should have provided the markers table. The `sacc` column is from the markers table. The kmer embedding is loaded already, so if you’ve copied and pasted from the docs, then the docs has the input paths wrong. Otherwise, the kmers table is loaded-in and then the markers table is trying to be loaded-in but fails as the incorrect file was provided.

The command should specify options first.

Usage:

```bash
usage: autometa-binning [-h] [--embedded-kmers EMBEDDED_KMERS]
                        [--embedding-method {bhsne,sksne,umap}]
                        [--clustering-method {dbscan,hdbscan}]
                        [--completeness COMPLETENESS] [--purity PURITY]
                        [--taxonomy TAXONOMY]
                        [--starting-rank {superkingdom,phylum,class,order,family,genus,species}]
                        [--reverse-ranks] [--domain {bacteria,archaea}]
                        [--verbose]
                        kmers coverage markers out

Perform marker gene guided binning of metagenome contigs using annotations
(when available) of sequence composition, coverage and homology.

positional arguments:
  kmers                 </path/to/normalized/kmers.tsv>
  coverage              </path/to/coverages.tsv>
  markers               </path/to/markers.tsv>
  out                   </path/to/output.tsv>

optional arguments:
  -h, --help            show this help message and exit
  --embedded-kmers EMBEDDED_KMERS
                        </path/to/embedded_kmers.tsv> (default: None)
  --embedding-method {bhsne,sksne,umap}
                        Embedding method to use (default: bhsne)
  --clustering-method {dbscan,hdbscan}
                        Clustering method to use (default: dbscan)
  --completeness COMPLETENESS
                        <completeness cutoff> (default: 20.0)
  --purity PURITY       <purity cutoff> (default: 90.0)
  --taxonomy TAXONOMY   </path/to/taxonomy.tsv> (default: None)
  --starting-rank {superkingdom,phylum,class,order,family,genus,species}
                        Canonical rank at which to begin subsetting taxonomy
                        (default: superkingdom)
  --reverse-ranks       Reverse order at which to split taxonomy by canonical-
                        rank. When --reverse-ranks given, contigs will be
                        split in order of species, genus, family, order,
                        class, phylum, superkingdom. (default: False)
  --domain {bacteria,archaea}
                        Kingdom to consider (archaea|bacteria) (default:
                        bacteria)
  --verbose             log debug information (default: False)
```

```bash
autometa-binning \
    --embedded-kmers embedded_kmers.tsv \
    --taxonomy taxonomy.tsv.gz \
    --clustering-method dbscan \
    --domain bacteria \
    kmers_norm.tsv coverage_table.tsv markers.tsv.gz bacteria_binning.tsv
```

**Comment by jason-c-kwan** [comment]
I think there might be something wrong with the format of the markers table from the Google Drive (78 Mbp dataset). I do this:

```
autometa-binning --embedded-kmers embedded_kmers.tsv --taxonomy taxonomy.tsv.gz --clustering-method dbscan --domain bacteria kmers_norm.tsv coverage_table.tsv markers.tsv.gz bacteria_binning.tsv
```

And I get this:

```
[03/12/2021 07:23:34 PM DEBUG] autometa.common.kmers: k-mers frequency embedding already exists embedded_kmers.tsv
Traceback (most recent call last):
  File "/opt/conda/bin/autometa-binning", line 33, in <module>
    sys.exit(load_entry_point('Autometa==2.0a0', 'console_scripts', 'autometa-binning')())
  File "/opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/binning/recursive_dbscan.py", line 787, in main
    markers_df = load_markers(args.markers)
  File "/opt/conda/lib/python3.8/site-packages/Autometa-2.0a0-py3.8.egg/autometa/common/markers.py", line 76, in load
    grouped_df = df.groupby("contig")["sacc"]
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 1542, in __getitem__
    return super().__getitem__(key)
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/base.py", line 280, in __getitem__
    raise KeyError(f"Column not found: {key}")
KeyError: 'Column not found: sacc'
```

This is the format of the Google drive table:

```
(base) root@4d4d64742d86:/test_data# zcat markers.tsv.gz | head
contig	single_copy_PFAMs	num_single_copies
NODE_1_length_1389215_cov_225.275	PF01783.18,PF00164.20,PF00466.15,PF00113.17,PF00298.14,PF04998.12,PF06071.8,PF03461.10,PF00830.14,PF00830.14,PF02873.11,PF04983.13,PF04565.11,PF04560.15,PF04997.7,PF00035.20,PF04563.10,PF00687.16,PF05000.12,PF03952.11,PF01084.15,PF00562.23,PF01025.14,PF10385.4,PF03946.9,PF00627.26,PF00344.15,PF00177.16,PF00584.15,PF00623.15,PF01195.14,PF00542.14,PF04561.9	33
NODE_2_length_1166739_cov_224.155	PF01783.18,PF00154.16,PF00162.14,PF00113.17,PF01018.17,PF01765.14,PF00889.14,PF01409.15,PF00958.17,PF01715.12,PF03461.10,PF02873.11,PF03484.10,PF01016.14,PF10458.4,PF03772.11,PF03485.11,PF03147.9,PF00380.14,PF03952.11,PF06689.8,PF00750.14,PF01632.14,PF00572.13,PF00453.13,PF08275.6,PF00627.26,PF00318.15,PF02912.13,PF01795.14,PF00829.16	31
NODE_3_length_1063064_cov_225.095	PF03602.10,PF01783.18,PF06574.7,PF00154.16,PF01509.13,PF01765.14,PF00889.14,PF01715.12,PF08529.6,PF00830.14,PF01668.13,PF01746.16,PF00035.20,PF11987.3,PF00312.17,PF01782.13,PF00886.14,PF01245.15,PF01687.12,PF03726.9,PF00627.26,PF04760.10,PF00318.15,PF02978.14,PF02033.13	25
NODE_4_length_1031470_cov_223.812	PF06574.7,PF01509.13,PF00162.14,PF02938.9,PF00958.17,PF01715.12,PF03461.10,PF08529.6,PF02873.11,PF00763.18,PF00763.18,PF01668.13,PF02130.12,PF01746.16,PF10458.4,PF11987.3,PF03485.11,PF03840.9,PF01782.13,PF00886.14,PF01649.13,PF00380.14,PF00121.13,PF02882.14,PF02882.14,PF00750.14,PF01687.12,PF00572.13,PF08459.6,PF04760.10,PF01795.14	31
NODE_5_length_937195_cov_225.122	PF00252.13,PF00237.14,PF00276.15,PF00338.17,PF03947.13,PF00181.18,PF00831.18,PF02132.10,PF02403.17,PF00366.15,PF00297.17,PF00627.26,PF00203.16,PF00573.17,PF00189.15	15
NODE_6_length_801699_cov_224.213	PF01018.17,PF01016.14,PF02130.12,PF10458.4,PF03772.11,PF02410.10,PF05698.9,PF01649.13,PF06689.8,PF06421.7,PF05697.8,PF08275.6,PF04760.10,PF00829.16	14
NODE_7_length_734119_cov_224.107	PF01176.14	1
NODE_8_length_686892_cov_223.785	PF12344.3,PF03602.10,PF01281.14,PF01409.15,PF06071.8,PF00958.17,PF01715.12,PF03461.10,PF03484.10,PF01330.16,PF01016.14,PF01668.13,PF03652.10,PF02130.12,PF02410.10,PF07499.8,PF03147.9,PF02132.10,PF05698.9,PF03948.9,PF00380.14,PF06689.8,PF02403.17,PF05697.8,PF01084.15,PF01632.14,PF01025.14,PF00572.13,PF01416.15,PF02224.13,PF00453.13,PF01250.12,PF08275.6,PF08459.6,PF05491.8,PF02978.14,PF02912.13,PF01195.14,PF01176.14,PF05198.11,PF00707.17,PF00829.16	42
NODE_9_length_644926_cov_224.104	PF03602.10,PF01783.18,PF06574.7,PF00154.16,PF01509.13,PF02938.9,PF01018.17,PF01765.14,PF00889.14,PF01121.15,PF06071.8,PF01715.12,PF08529.6,PF00830.14,PF01330.16,PF01016.14,PF00763.18,PF03652.10,PF02130.12,PF01746.16,PF00035.20,PF11987.3,PF03772.11,PF00312.17,PF02410.10,PF07499.8,PF01782.13,PF00886.14,PF01649.13,PF01245.15,PF06421.7,PF01252.13,PF02882.14,PF01687.12,PF01025.14,PF02224.13,PF08275.6,PF03726.9,PF00627.26,PF00627.26,PF04760.10,PF00318.15,PF05491.8,PF02978.14,PF02033.13,PF01795.14,PF00829.16	47
```
