### ISSUE TITLE
Add helpful error message

### ISSUE THREAD

**Issue by chasemc** [KwanLab/Autometa#306]
https://github.com/KwanLab/Autometa/blob/baf61c04dddf5b33bb825dba2841de1e38dffefe/autometa/validation/datasets.py#L47

Currently the error has to be traced back to the code:
```
Traceback (most recent call last):
  File "/home/chase/miniconda3/envs/autometa/bin/autometa-download-dataset", line 8, in <module>
    sys.exit(main())
  File "/home/chase/miniconda3/envs/autometa/lib/python3.10/site-packages/autometa/validation/datasets.py", line 197, in main
    download(
  File "/home/chase/miniconda3/envs/autometa/lib/python3.10/site-packages/autometa/validation/datasets.py", line 47, in download
    raise NotImplementedError
NotImplementedError
```

**Comment by chasemc** [comment]
Example of how to do so:
https://github.com/KwanLab/Autometa/blob/52fd5b0586b4b8bdf71f7b5fa34201f8735b5fa6/autometa/common/utilities.py#L211
